--- #YAML:1.0
name:                Perl-Destruct-Level
version:             0.02
abstract:            ~
license:             ~
author:              
    - Rafael Garcia-Suarez <rgarciasuarez@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.38
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
